name: Checks

on:
  schedule:
    - cron: 0 10 1,15 * *

jobs:
  phpunit:
    name: Check of Emoji list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: curl, mbstring, zlib
          tools: composer:v2

      - run: composer update --no-progress

      - run: vendor/bin/phpunit --testsuite=check --no-coverage
